### ISSUE TITLE
Sadly InsertAll not useable in real life application

### ISSUE THREAD

**Issue by ErikEJ** [MikaelEliasson/EntityFramework.Utilities#78]
I really wanted to use this, but it is missing some essential features, that are needed in real-life apps:
Support for SqlTransaction from the outer DbContext
Support for enforcing constraints

**Comment by ewassef** [comment]
What if you wrapped that call in a [TransactionScope](https://msdn.microsoft.com/en-us/library/system.transactions.transactionscope(v=vs.110).aspx)

Also, bulk inserts dont respect constraints by design... even if you do this through raw ado, itll have the same behavior.. so, you would need to validate in code.

**Comment by ErikEJ** [comment]
I need to avoid transactionscope, and sqlbulkcopy DOES support enforcing constractions and respects a sqltransaction

**Comment by ewassef** [comment]
I want wasn't aware you could pass in options. In that case, you can probably add an optional parameter to the call and pass those along. Seems like a simple fix

**Comment by ErikEJ** [comment]
Giving up, seems like this project has been abandoned
