### ISSUE TITLE
This seems to be stagnant but is still useful.... 

### ISSUE THREAD

**Issue by ewassef** [MikaelEliasson/EntityFramework.Utilities#99]
@MikaelEliasson and others, Do you want to let someone else help you with this and maintain it?
I am ready to help as I need this on a day to day basis and want to add some of the features in the outstanding PR's

If enough people upvote,  I can fork it and maintain this as a V2 or something until we can reach @MikaelEliasson

**Comment by schweinsbauch** [comment]
@ewassef : are you still interessted in forking? we also plan to use this, but sadly it's not maintened

**Comment by phillijw** [comment]
Someone certainly needs to do something... I'd be willing to put in a little time here and there as well.

**Comment by RudeySH** [comment]
I am currently maintaining a fork. See [RudeySH/EntityFramework.Utilities](https://github.com/RudeySH/EntityFramework.Utilities).

Right now, the following issues/PRs are fixed in my fork: #32, #34, #56, #57, #60, #61, #71, #72, #84, #96, #112, #113, #115, #116.

EDIT: And for a while now there's also a NuGet package available! https://www.nuget.org/packages/RudeySH.EFUtilities/
